# Generated by Django 6.0.6 on 2026-06-25 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
        ('teams', '0004_rename_tournament_squad_id_tournamentsquad_squad_id'),
        ('tournaments', '0002_rename_standing_id_tournamentstanding_tournament_standing_id'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_type', models.CharField(choices=[('LEAGUE', 'League'), ('QUALIFIER', 'Qualifier'), ('QUARTERFINAL', 'Quarterfinal'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], default='LEAGUE', max_length=20)),
                ('round_number', models.SmallIntegerField(default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('innings_count', models.SmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='SCHEDULED', max_length=20)),
                ('result_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.group')),
                ('primary_umpire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umpired_matches', to=settings.AUTH_USER_MODEL)),
                ('runnerup_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_runner_up', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='venues.venue')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='teams.team')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'matches',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('innings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innings_number', models.SmallIntegerField()),
                ('overs_completed', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_super_over', models.BooleanField(default=False)),
                ('total_score', models.SmallIntegerField(default=0)),
                ('total_sixes', models.SmallIntegerField(default=0)),
                ('total_fours', models.SmallIntegerField(default=0)),
                ('total_wickets', models.SmallIntegerField(default=0)),
                ('total_extras', models.IntegerField(default=0)),
                ('total_wides', models.IntegerField(default=0)),
                ('total_noballs', models.IntegerField(default=0)),
                ('target_runs', models.SmallIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_batted', to='teams.team')),
                ('fielding_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_fielded', to='teams.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='matches.match')),
            ],
            options={
                'verbose_name': 'Innings',
                'verbose_name_plural': 'Innings',
                'db_table': 'innings',
                'ordering': ['match', 'innings_number'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ball_sequence', models.IntegerField()),
                ('over_number', models.SmallIntegerField()),
                ('ball_number', models.SmallIntegerField()),
                ('runs_scored', models.SmallIntegerField(default=0)),
                ('extra_type', models.CharField(choices=[('WIDE', 'Wide'), ('NO_BALL', 'No Ball'), ('BYE', 'Bye'), ('LEG_BYE', 'Leg Bye'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('is_legal_delivery', models.GeneratedField(db_persist=True, expression=models.Case(models.When(extra_type__in=['WIDE', 'NO_BALL'], then=models.Value(False)), default=models.Value(True)), output_field=models.BooleanField())),
                ('wicket_type', models.CharField(choices=[('BOWLED', 'Bowled'), ('CAUGHT', 'Caught'), ('LBW', 'LBW'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit Wicket'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('is_wicket', models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=models.Value(False), wicket_type='NONE'), default=models.Value(True)), output_field=models.BooleanField())),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='matches.innings')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='matches.match')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'deliveries',
                'ordering': ['innings', 'ball_sequence'],
            },
        ),
        migrations.CreateModel(
            name='MatchLiveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_bowling', to='players.player')),
                ('current_innings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matches.innings')),
                ('current_non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_non_striking', to='players.player')),
                ('current_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_striking', to='players.player')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='matches.match')),
            ],
            options={
                'db_table': 'match_live_states',
            },
        ),
        migrations.CreateModel(
            name='PlayerDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance_role', models.CharField(choices=[('STRIKER', 'Striker'), ('NON_STRIKER', 'Non Striker'), ('BOWLER', 'Bowler'), ('FIELDER_CATCH', 'Fielder Catch'), ('FIELDER_RUNOUT', 'Fielder Runout')], max_length=20)),
                ('runs_attributed', models.SmallIntegerField(default=0)),
                ('dismissal_info', models.CharField(blank=True, max_length=255)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_deliveries', to='matches.delivery')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_performances', to='players.player')),
            ],
            options={
                'verbose_name': 'Player delivery',
                'verbose_name_plural': 'Player deliveries',
                'db_table': 'player_deliveries',
            },
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10)),
                ('is_toss_winner', models.BooleanField(default=False)),
                ('toss_decision', models.CharField(blank=True, choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_matches', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_matches', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team match',
                'verbose_name_plural': 'Team matches',
                'db_table': 'team_matches',
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='matches_tournam_a71fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round_type'], name='matches_tournam_3eb471_idx'),
        ),
        migrations.AddIndex(
            model_name='innings',
            index=models.Index(fields=['match'], name='innings_match_i_5f15a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='innings',
            constraint=models.UniqueConstraint(fields=('match', 'innings_number'), name='unique_innings_number_per_match'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['match'], name='deliveries_match_i_92abc2_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['innings'], name='deliveries_innings_3ff0a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('innings', 'ball_sequence'), name='unique_ball_sequence_per_innings'),
        ),
        migrations.AddIndex(
            model_name='playerdelivery',
            index=models.Index(fields=['player'], name='player_deli_player__4280eb_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdelivery',
            index=models.Index(fields=['delivery'], name='player_deli_deliver_e2f045_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerdelivery',
            constraint=models.UniqueConstraint(fields=('delivery', 'player', 'performance_role'), name='unique_player_role_per_delivery'),
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='unique_team_per_match'),
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.UniqueConstraint(fields=('match', 'side'), name='unique_side_per_match'),
        ),
    ]
