# Generated by Django 6.0.6 on 2026-06-23 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_tournamentsquad'),
        ('tournaments', '0003_application_tournamentstanding'),
        ('venues', '0002_alter_venue_country_alter_venue_pincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('innings_count', models.SmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='SCHEDULED', max_length=20)),
                ('result_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_umpire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umpired_matches', to=settings.AUTH_USER_MODEL)),
                ('runnerup_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_lost', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='venues.venue')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='teams.team')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10)),
                ('is_toss_winner', models.BooleanField(default=False)),
                ('toss_decision', models.CharField(blank=True, choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_matches', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_matches', to='teams.team')),
            ],
            options={
                'db_table': 'team_matches',
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='matches_tournam_a71fc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='unique_team_per_match'),
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.UniqueConstraint(fields=('match', 'side'), name='unique_side_per_match'),
        ),
    ]
