# Generated by Django 6.0.6 on 2026-06-24 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ball_sequence', models.IntegerField()),
                ('over_number', models.SmallIntegerField()),
                ('ball_number', models.SmallIntegerField()),
                ('runs_scored', models.SmallIntegerField(default=0)),
                ('extra_runs', models.SmallIntegerField(default=0)),
                ('extra_type', models.CharField(choices=[('WIDE', 'Wide'), ('NO_BALL', 'No Ball'), ('BYE', 'Bye'), ('LEG_BYE', 'Leg Bye'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('is_legal_delivery', models.BooleanField(default=True)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(choices=[('BOWLED', 'Bowled'), ('CAUGHT', 'Caught'), ('LBW', 'LBW'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit Wicket'), ('NONE', 'None')], default='NONE', max_length=20)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'deliveries',
                'ordering': ['innings', 'ball_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('innings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innings_number', models.SmallIntegerField()),
                ('overs_completed', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_super_over', models.BooleanField(default=False)),
                ('total_score', models.SmallIntegerField(default=0)),
                ('total_sixes', models.SmallIntegerField(default=0)),
                ('total_fours', models.SmallIntegerField(default=0)),
                ('total_wickets', models.SmallIntegerField(default=0)),
                ('total_extras', models.IntegerField(default=0)),
                ('total_wides', models.IntegerField(default=0)),
                ('total_noballs', models.IntegerField(default=0)),
                ('target_runs', models.SmallIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Innings',
                'verbose_name_plural': 'Innings',
                'db_table': 'innings',
                'ordering': ['match', 'innings_number'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_type', models.CharField(choices=[('LEAGUE', 'League'), ('QUALIFIER', 'Qualifier'), ('QUARTERFINAL', 'Quarterfinal'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], default='LEAGUE', max_length=20)),
                ('round_number', models.SmallIntegerField(default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('innings_count', models.SmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='SCHEDULED', max_length=20)),
                ('result_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'matches',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchLiveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_runs', models.PositiveIntegerField(default=0)),
                ('balls_remaining', models.PositiveIntegerField(default=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match Live State',
                'verbose_name_plural': 'Match Live States',
                'db_table': 'match_live_states',
            },
        ),
        migrations.CreateModel(
            name='PlayerDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance_role', models.CharField(choices=[('STRIKER', 'Striker'), ('NON_STRIKER', 'Non Striker'), ('BOWLER', 'Bowler'), ('FIELDER_CATCH', 'Fielder Catch'), ('FIELDER_RUNOUT', 'Fielder Runout')], max_length=20)),
                ('runs_attributed', models.SmallIntegerField(default=0)),
                ('dismissal_info', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Player delivery',
                'verbose_name_plural': 'Player deliveries',
                'db_table': 'player_deliveries',
            },
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10)),
                ('is_toss_winner', models.BooleanField(default=False)),
                ('toss_decision', models.CharField(blank=True, choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=10)),
            ],
            options={
                'verbose_name': 'Team match',
                'verbose_name_plural': 'Team matches',
                'db_table': 'team_matches',
            },
        ),
    ]
