# Generated by Django 6.0.6 on 2026-06-24 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='innings',
            name='batting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_batted', to='teams.team'),
        ),
        migrations.AddField(
            model_name='innings',
            name='fielding_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_fielded', to='teams.team'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='matches.innings'),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.group'),
        ),
        migrations.AddField(
            model_name='match',
            name='primary_umpire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umpired_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='runnerup_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_runner_up', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='venues.venue'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='teams.team'),
        ),
        migrations.AddField(
            model_name='innings',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='matches.match'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchlivestate',
            name='current_bowler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_bowling', to='teams.tournamentsquad'),
        ),
        migrations.AddField(
            model_name='matchlivestate',
            name='current_innings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.innings'),
        ),
        migrations.AddField(
            model_name='matchlivestate',
            name='current_non_striker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_non_striking', to='teams.tournamentsquad'),
        ),
        migrations.AddField(
            model_name='matchlivestate',
            name='current_striker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_striking', to='teams.tournamentsquad'),
        ),
        migrations.AddField(
            model_name='matchlivestate',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='matches.match'),
        ),
        migrations.AddField(
            model_name='playerdelivery',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_deliveries', to='matches.delivery'),
        ),
        migrations.AddField(
            model_name='playerdelivery',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_performances', to='players.player'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_matches', to='matches.match'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_matches', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='matches_tournam_a71fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round_type'], name='matches_tournam_3eb471_idx'),
        ),
        migrations.AddIndex(
            model_name='innings',
            index=models.Index(fields=['match'], name='innings_match_i_5f15a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='innings',
            constraint=models.UniqueConstraint(fields=('match', 'innings_number'), name='unique_innings_number_per_match'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['match'], name='deliveries_match_i_92abc2_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['innings'], name='deliveries_innings_3ff0a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('innings', 'ball_sequence'), name='unique_ball_sequence_per_innings'),
        ),
        migrations.AddIndex(
            model_name='playerdelivery',
            index=models.Index(fields=['player'], name='player_deli_player__4280eb_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdelivery',
            index=models.Index(fields=['delivery'], name='player_deli_deliver_e2f045_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerdelivery',
            constraint=models.UniqueConstraint(fields=('delivery', 'player', 'performance_role'), name='unique_player_role_per_delivery'),
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='unique_team_per_match'),
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.UniqueConstraint(fields=('match', 'side'), name='unique_side_per_match'),
        ),
    ]
