# Generated by Django 6.0.6 on 2026-06-24 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0003_tournamentsquad'),
        ('tournaments', '0003_application_tournamentstanding'),
        ('venues', '0002_alter_venue_country_alter_venue_pincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ball_sequence', models.IntegerField()),
                ('over_number', models.SmallIntegerField()),
                ('ball_number', models.SmallIntegerField()),
                ('runs_scored', models.SmallIntegerField(default=0)),
                ('extra_runs', models.SmallIntegerField(default=0)),
                ('extra_type', models.CharField(choices=[('WIDE', 'Wide'), ('NO_BALL', 'No Ball'), ('BYE', 'Bye'), ('LEG_BYE', 'Leg Bye'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('is_legal_delivery', models.BooleanField(default=True)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(choices=[('BOWLED', 'Bowled'), ('CAUGHT', 'Caught'), ('LBW', 'LBW'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit Wicket'), ('NONE', 'None')], default='NONE', max_length=20)),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['innings', 'ball_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('innings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innings_number', models.SmallIntegerField()),
                ('overs_completed', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_score', models.SmallIntegerField(default=0)),
                ('total_sixes', models.SmallIntegerField(default=0)),
                ('total_fours', models.SmallIntegerField(default=0)),
                ('total_wickets', models.SmallIntegerField(default=0)),
                ('total_extras', models.IntegerField(default=0)),
                ('total_wides', models.IntegerField(default=0)),
                ('total_noballs', models.IntegerField(default=0)),
                ('target_runs', models.SmallIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'innings',
                'ordering': ['match', 'innings_number'],
            },
        ),
        migrations.CreateModel(
            name='PlayerDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance_role', models.CharField(choices=[('STRIKER', 'Striker'), ('NON_STRIKER', 'Non Striker'), ('BOWLER', 'Bowler'), ('FIELDER_CATCH', 'Fielder Catch'), ('FIELDER_RUNOUT', 'Fielder Runout')], max_length=20)),
                ('runs_attributed', models.SmallIntegerField(default=0)),
                ('dismissal_info', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'player_deliveries',
            },
        ),
        migrations.RemoveField(
            model_name='match',
            name='runnerup_team',
        ),
        migrations.AddField(
            model_name='match',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='round_type',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('QUALIFIER', 'Qualifier'), ('QUARTERFINAL', 'Quarterfinal'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], default='LEAGUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round_type'], name='matches_tournam_3eb471_idx'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='matches.match'),
        ),
        migrations.AddField(
            model_name='innings',
            name='batting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_batted', to='teams.team'),
        ),
        migrations.AddField(
            model_name='innings',
            name='fielding_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_fielded', to='teams.team'),
        ),
        migrations.AddField(
            model_name='innings',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='matches.match'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='matches.innings'),
        ),
        migrations.AddField(
            model_name='playerdelivery',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_deliveries', to='matches.delivery'),
        ),
        migrations.AddField(
            model_name='playerdelivery',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_performances', to='players.player'),
        ),
        migrations.AddIndex(
            model_name='innings',
            index=models.Index(fields=['match'], name='innings_match_i_5f15a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='innings',
            constraint=models.UniqueConstraint(fields=('match', 'innings_number'), name='unique_innings_number_per_match'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['match'], name='deliveries_match_i_92abc2_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['innings'], name='deliveries_innings_3ff0a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('innings', 'ball_sequence'), name='unique_ball_sequence_per_innings'),
        ),
        migrations.AddIndex(
            model_name='playerdelivery',
            index=models.Index(fields=['player'], name='player_deli_player__4280eb_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdelivery',
            index=models.Index(fields=['delivery'], name='player_deli_deliver_e2f045_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerdelivery',
            constraint=models.UniqueConstraint(fields=('delivery', 'player', 'performance_role'), name='unique_player_role_per_delivery'),
        ),
    ]
