# Generated by Django 6.0.6 on 2026-06-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_delivery_innings_playerdelivery_and_more'),
        ('teams', '0003_tournamentsquad'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_runner_up', to='teams.team'),
        ),
    ]
