# Generated by Django 6.0.6 on 2026-06-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='standings_applied',
            field=models.BooleanField(default=False),
        ),
    ]
