# Generated by Django 6.0.6 on 2026-06-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_runner_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['innings', 'ball_sequence'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='innings',
            options={'ordering': ['match', 'innings_number'], 'verbose_name': 'Innings', 'verbose_name_plural': 'Innings'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['start_date'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='playerdelivery',
            options={'verbose_name': 'Player Delivery', 'verbose_name_plural': 'Player Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='teammatch',
            options={'verbose_name': 'Team Match', 'verbose_name_plural': 'Team Matches'},
        ),
    ]
