# Generated by Django 6.0.6 on 2026-06-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_standings_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_boundary',
            field=models.BooleanField(default=False),
        ),
    ]
