# Generated by Django 6.0.6 on 2026-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_delivery_is_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
