# Generated by Django 6.0.6 on 2026-06-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_delivery_options_alter_innings_options_and_more'),
        ('teams', '0003_tournamentsquad'),
        ('tournaments', '0004_group_tournamentstanding_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerdelivery',
            options={'verbose_name': 'Player delivery', 'verbose_name_plural': 'Player deliveries'},
        ),
        migrations.AlterModelOptions(
            name='teammatch',
            options={'verbose_name': 'Team match', 'verbose_name_plural': 'Team matches'},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='runner_up',
            new_name='runnerup_team',
        ),
        migrations.AddField(
            model_name='innings',
            name='is_super_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.group'),
        ),
        migrations.CreateModel(
            name='MatchLiveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_runs', models.PositiveIntegerField(default=0)),
                ('balls_remaining', models.PositiveIntegerField(default=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_bowling', to='teams.tournamentsquad')),
                ('current_innings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.innings')),
                ('current_non_striker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_non_striking', to='teams.tournamentsquad')),
                ('current_striker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_striking', to='teams.tournamentsquad')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='matches.match')),
            ],
            options={
                'verbose_name': 'Match Live State',
                'verbose_name_plural': 'Match Live States',
                'db_table': 'match_live_states',
            },
        ),
    ]
