# Generated by Django 6.0.6 on 2026-07-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_teammatch_is_paused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammatch',
            name='is_paused',
        ),
        migrations.AddField(
            model_name='match',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
