# Generated by Django 6.0.6 on 2026-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_remove_teammatch_is_paused_match_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
