# Generated by Django 6.0.6 on 2026-06-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsquad',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_entries', to='tournaments.application'),
        ),
        migrations.AddField(
            model_name='tournamentsquad',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_entries', to='players.player'),
        ),
        migrations.AddField(
            model_name='tournamentsquad',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_squads', to='teams.team'),
        ),
        migrations.AddField(
            model_name='tournamentsquad',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_entries', to='tournaments.tournament'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['city'], name='teams_city_aab8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='teams_is_acti_dd3222_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentsquad',
            index=models.Index(fields=['tournament', 'team'], name='tournament__tournam_e3f08a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentsquad',
            constraint=models.UniqueConstraint(fields=('tournament', 'player'), name='unique_player_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamentsquad',
            constraint=models.UniqueConstraint(fields=('tournament', 'team', 'jersey_number'), name='unique_jersey_per_team_per_tournament'),
        ),
    ]
