# Generated by Django 6.0.6 on 2026-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentsquad',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tournamentsquad',
            old_name='squad_id',
            new_name='tournament_squad_id',
        ),
        migrations.AddField(
            model_name='tournamentsquad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
