# Generated by Django 6.0.6 on 2026-06-23 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0002_alter_team_team_head'),
        ('tournaments', '0003_application_tournamentstanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentSquad',
            fields=[
                ('squad_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('squad_role', models.CharField(choices=[('PLAYER', 'Player'), ('CAPTAIN', 'Captain'), ('VICE_CAPTAIN', 'Vice Captain')], default='PLAYER', max_length=20)),
                ('is_wicketkeeper', models.BooleanField(default=False)),
                ('is_playing_xi', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_entries', to='tournaments.application')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_entries', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_squads', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_entries', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_squads',
                'ordering': ['team', 'jersey_number'],
                'indexes': [models.Index(fields=['tournament', 'team'], name='tournament__tournam_e3f08a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'player'), name='unique_player_per_tournament'), models.UniqueConstraint(fields=('tournament', 'team', 'jersey_number'), name='unique_jersey_per_team_per_tournament')],
            },
        ),
    ]
