# Generated by Django 6.0.6 on 2026-06-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_added_at_tournamentsquad_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentsquad',
            old_name='tournament_squad_id',
            new_name='squad_id',
        ),
    ]
