# Generated by Django 6.0.6 on 2026-06-27 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_rename_tournament_squad_id_tournamentsquad_squad_id'),
        ('tournaments', '0002_rename_standing_id_tournamentstanding_tournament_standing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentsquad',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_entries', to='tournaments.application'),
        ),
    ]
