# Generated by Django 6.0.6 on 2026-06-24 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('regulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_format', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('TEST', 'Test'), ('T10', 'T10'), ('CUSTOM', 'Custom')], default='T20', max_length=10)),
                ('overs_per_innings', models.SmallIntegerField(blank=True, null=True)),
                ('innings_per_match', models.SmallIntegerField(default=1)),
                ('max_overs_per_bowler', models.SmallIntegerField(blank=True, null=True)),
                ('max_bouncers_per_over', models.SmallIntegerField(default=0)),
                ('players_per_side', models.SmallIntegerField(default=11)),
                ('wide_value', models.SmallIntegerField(default=1)),
                ('noball_free_hit_enabled', models.BooleanField(default=True)),
                ('noball_value', models.SmallIntegerField(default=1)),
                ('powerplay_config', models.JSONField(default=dict)),
                ('drs_per_innings', models.SmallIntegerField(default=2)),
                ('timed_out_limit', models.SmallIntegerField(default=180)),
                ('super_over_enabled', models.BooleanField(default=False)),
                ('custom_regulations', models.JSONField(default=dict)),
                ('tournament_format', models.CharField(choices=[('LEAGUE', 'League (Round Robin)'), ('KNOCKOUT', 'Knockout'), ('GROUP_KNOCKOUT', 'Group Stage + Knockout'), ('DOUBLE_ELIMINATION', 'Double Elimination')], default='LEAGUE', max_length=20)),
                ('teams_per_group', models.SmallIntegerField(blank=True, null=True)),
                ('teams_qualifying_per_group', models.SmallIntegerField(blank=True, null=True)),
                ('min_teams', models.SmallIntegerField(default=2)),
                ('max_teams', models.SmallIntegerField(blank=True, null=True)),
                ('points_for_win', models.SmallIntegerField(default=2)),
                ('points_for_tie', models.SmallIntegerField(default=1)),
                ('points_for_loss', models.SmallIntegerField(default=0)),
                ('points_for_no_result', models.SmallIntegerField(default=1)),
                ('points_penalty_for_forfeit', models.SmallIntegerField(default=0)),
                ('tiebreaker_order', models.JSONField(blank=True, default=list)),
                ('over_rate_penalty_enabled', models.BooleanField(default=False)),
                ('over_rate_penalty_points', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'regulations',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('INTER_COLLEGE', 'Inter College'), ('INTER_SCHOOL', 'Inter School'), ('CLUB_LEVEL', 'Club Level'), ('DISTRICT_LEVEL', 'District Level'), ('STATE_LEVEL', 'State Level'), ('NATIONAL_LEVEL', 'National Level'), ('CORPORATE_LEVEL', 'Corporate level'), ('OPEN', 'Open')], max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACCEPTING_APPLICATIONS', 'Accepting Applications'), ('APPLICATIONS_CLOSED', 'Applications Closed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=30)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_public', models.BooleanField(default=True)),
                ('application_starts_from', models.DateTimeField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.regulation')),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_name', models.CharField(max_length=255)),
                ('registered_short_name', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_applications', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_applications', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentOrganizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('institution_type', models.CharField(blank=True, choices=[('UNIVERSITY', 'University'), ('SCHOOL', 'School'), ('CLUB', 'Club'), ('SPORTS_BOARD', 'Sports Board'), ('CORPORATE', 'Corporate'), ('OTHER', 'Other')], max_length=20)),
                ('institution_email', models.EmailField(blank=True, max_length=254)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournament_organizers',
            },
        ),
        migrations.CreateModel(
            name='TournamentStanding',
            fields=[
                ('standing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matches_played', models.SmallIntegerField(default=0)),
                ('matches_won', models.SmallIntegerField(default=0)),
                ('matches_lost', models.SmallIntegerField(default=0)),
                ('matches_tied', models.SmallIntegerField(default=0)),
                ('matches_no_result', models.SmallIntegerField(default=0)),
                ('points', models.SmallIntegerField(default=0)),
                ('net_run_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standings', to='tournaments.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_standings', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_standings',
                'ordering': ['-points', '-net_run_rate'],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_group_name_per_tournament'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_e61111_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tournament', 'status'], name='application_tournam_15bdf8_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('team', 'tournament'), name='unique_team_tournament_application'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('tournament', 'registered_name'), name='unique_team_name_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('tournament', 'registered_short_name'), name='unique_short_name_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamentorganizer',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='unique_organizer_per_tournament'),
        ),
        migrations.AddIndex(
            model_name='tournamentstanding',
            index=models.Index(fields=['tournament', '-points'], name='tournament__tournam_1e92a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstanding',
            constraint=models.UniqueConstraint(fields=('tournament', 'team'), name='unique_tournament_team_standing'),
        ),
    ]
