# Generated by Django 6.0.6 on 2026-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('regulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_format', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('TEST', 'Test'), ('T10', 'T10'), ('CUSTOM', 'Custom')], default='T20', max_length=10)),
                ('overs_per_innings', models.SmallIntegerField(blank=True, null=True)),
                ('innings_per_match', models.SmallIntegerField(default=1)),
                ('max_overs_per_bowler', models.SmallIntegerField(blank=True, null=True)),
                ('max_bouncers_per_over', models.SmallIntegerField(default=0)),
                ('players_per_side', models.SmallIntegerField(default=11)),
                ('wide_value', models.SmallIntegerField(default=1)),
                ('noball_free_hit_enabled', models.BooleanField(default=True)),
                ('noball_value', models.SmallIntegerField(default=1)),
                ('overthrow_runs_enabled', models.BooleanField(default=True)),
                ('powerplay_config', models.JSONField(default=dict)),
                ('drs_per_innings', models.SmallIntegerField(default=2)),
                ('timed_out_limit', models.SmallIntegerField(default=180)),
                ('super_over_enabled', models.BooleanField(default=False)),
                ('custom_regulations', models.JSONField(default=dict)),
                ('tournament_format', models.CharField(choices=[('LEAGUE', 'League (Round Robin)'), ('KNOCKOUT', 'Knockout'), ('GROUP_KNOCKOUT', 'Group Stage + Knockout'), ('DOUBLE_ELIMINATION', 'Double Elimination')], default='LEAGUE', max_length=20)),
                ('teams_per_group', models.SmallIntegerField(blank=True, null=True)),
                ('teams_qualifying_per_group', models.SmallIntegerField(blank=True, null=True)),
                ('min_teams', models.SmallIntegerField(default=2)),
                ('max_teams', models.SmallIntegerField(blank=True, null=True)),
                ('points_for_win', models.SmallIntegerField(default=2)),
                ('points_for_tie', models.SmallIntegerField(default=1)),
                ('points_for_loss', models.SmallIntegerField(default=0)),
                ('points_for_no_result', models.SmallIntegerField(default=1)),
                ('points_penalty_for_forfeit', models.SmallIntegerField(default=0)),
                ('tiebreaker_order', models.JSONField(blank=True, default=list)),
                ('over_rate_penalty_enabled', models.BooleanField(default=False)),
                ('over_rate_penalty_points', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'regulations',
            },
        ),
    ]
