# Generated by Django 6.0.6 on 2026-06-22 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='overthrow_runs_enabled',
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('INTER_COLLEGE', 'Inter College'), ('INTER_SCHOOL', 'Inter School'), ('CLUB_LEVEL', 'Club Level'), ('DISTRICT_LEVEL', 'District Level'), ('STATE_LEVEL', 'State Level'), ('NATIONAL_LEVEL', 'National Level'), ('CORPORATE_LEVEL', 'Corporate level'), ('OPEN', 'Open')], max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACCEPTING_APPLICATIONS', 'Accepting Applications'), ('APPLICATIONS_CLOSED', 'Applications Closed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=30)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_public', models.BooleanField(default=True)),
                ('application_starts_from', models.DateTimeField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.regulation')),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentOrganizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('institution_type', models.CharField(blank=True, choices=[('UNIVERSITY', 'University'), ('SCHOOL', 'School'), ('CLUB', 'Club'), ('SPORTS_BOARD', 'Sports Board'), ('CORPORATE', 'Corporate'), ('OTHER', 'Other')], max_length=20)),
                ('institution_email', models.EmailField(blank=True, max_length=254)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournament_organizers',
                'constraints': [models.UniqueConstraint(fields=('tournament', 'user'), name='unique_organizer_per_tournament')],
            },
        ),
    ]
