# Generated by Django 6.0.6 on 2026-06-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentstanding',
            old_name='standing_id',
            new_name='tournament_standing_id',
        ),
    ]
