# Generated by Django 6.0.6 on 2026-06-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_rename_standing_id_tournamentstanding_tournament_standing_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regulation',
            constraint=models.CheckConstraint(condition=models.Q(('overs_per_innings__gt', 0), ('match_format', 'TEST'), _connector='OR'), name='overs_per_innings_positive_unless_test'),
        ),
        migrations.AddConstraint(
            model_name='regulation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_format', 'TEST'), ('overs_per_innings__isnull', True)), models.Q(models.Q(('match_format', 'TEST'), _negated=True), ('overs_per_innings__gt', 0)), _connector='OR'), name='overs_per_innings_valid_per_format'),
        ),
    ]
