# Generated by Django 6.0.6 on 2026-06-23 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_team_head'),
        ('tournaments', '0002_remove_regulation_overthrow_runs_enabled_tournament_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_applications', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_applications', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='application_status_e61111_idx'), models.Index(fields=['tournament', 'status'], name='application_tournam_15bdf8_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'tournament'), name='unique_team_tournament_application')],
            },
        ),
        migrations.CreateModel(
            name='TournamentStanding',
            fields=[
                ('standing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matches_played', models.SmallIntegerField(default=0)),
                ('matches_won', models.SmallIntegerField(default=0)),
                ('matches_lost', models.SmallIntegerField(default=0)),
                ('matches_tied', models.SmallIntegerField(default=0)),
                ('matches_no_result', models.SmallIntegerField(default=0)),
                ('points', models.SmallIntegerField(default=0)),
                ('net_run_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_standings', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_standings',
                'ordering': ['-points', '-net_run_rate'],
                'indexes': [models.Index(fields=['tournament', '-points'], name='tournament__tournam_1e92a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'team'), name='unique_tournament_team_standing')],
            },
        ),
    ]
