# Generated by Django 6.0.6 on 2026-06-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_regulation_overs_per_innings_positive_unless_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulation',
            old_name='innings_per_match',
            new_name='innings_per_team',
        ),
    ]
