# Generated by Django 6.0.6 on 2026-06-29 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_rename_innings_per_match_regulation_innings_per_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='created_by',
            field=models.ForeignKey(default='4d3a4418-47e7-4ec6-b709-120e0f9a4cec', on_delete=django.db.models.deletion.CASCADE, related_name='regulator', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
    ]
