# Generated by Django 6.0.6 on 2026-07-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='player_min_age',
            field=models.SmallIntegerField(default=16),
        ),
    ]
