# Generated by Django 6.0.6 on 2026-07-07 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_regulation_player_min_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regulation',
            constraint=models.CheckConstraint(condition=models.Q(('player_min_age__isnull', True), ('player_min_age__gte', 0), _connector='OR'), name='player_min_age_non_negative'),
        ),
    ]
