# Generated by Django 6.0.6 on 2026-07-07 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_team_created_by'),
        ('tournaments', '0008_regulation_player_min_age_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to='teams.team'),
        ),
    ]
