# Generated by Django 6.0.6 on 2026-06-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ORGANIZER', 'TEAMHEAD', 'UMPIRE', 'VIEWER'])), name='valid_user_role'),
        ),
    ]
