# Generated by Django 6.0.6 on 2026-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_valid_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='valid_user_role',
        ),
        migrations.AddField(
            model_name='user',
            name='apply_for',
            field=models.CharField(blank=True, choices=[('ORGANIZER', 'Organizer'), ('TEAMHEAD', 'TeamHead'), ('UMPIRE', 'Umpire')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ORGANIZER', 'Organizer'), ('TEAMHEAD', 'TeamHead'), ('UMPIRE', 'Umpire'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['PENDING', 'ORGANIZER', 'TEAMHEAD', 'UMPIRE', 'REJECTED'])), name='valid_user_role'),
        ),
    ]
