# Generated by Django 6.0.6 on 2026-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_valid_user_role_user_apply_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apply_for',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('TEAMHEAD', 'TeamHead'), ('UMPIRE', 'Umpire')], max_length=20),
        ),
    ]
