# Generated by Django 6.0.6 on 2026-06-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_apply_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apply_for',
        ),
    ]
