# Generated by Django 6.0.6 on 2026-06-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_apply_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apply_for',
            field=models.CharField(blank=True, choices=[('ORGANIZER', 'Organizer'), ('TEAMHEAD', 'TeamHead'), ('UMPIRE', 'Umpire')], default='TEAMHEAD', max_length=20, null=True),
        ),
    ]
