# Generated by Django 6.0.6 on 2026-06-23 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_alter_team_team_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('player_role', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All Rounder'), ('WICKETKEEPER', 'Wicketkeeper')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='player_documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster', to='teams.team')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['current_team'], name='players_current_024c8d_idx'), models.Index(fields=['is_active'], name='players_is_acti_29de7e_idx')],
            },
        ),
    ]
