# Generated by Django 6.0.6 on 2026-06-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['current_team'], name='players_current_024c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_active'], name='players_is_acti_29de7e_idx'),
        ),
    ]
